server:
  port: 8080
spring:
  application:
    name: report-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://leiziyan.zy.com:3306/report?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    username: root
    password: P@ssw0rd
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml